// src/lib/profileOptions.ts

// Interest keys (must match flattened keys in i18n dict)
export const INTEREST_KEYS = [
  "opt.int.dorama",
  "opt.int.anime",
  "opt.int.marvel",
  "opt.int.cinema",
  "opt.int.truecrime",
  "opt.int.netflix",
  "opt.int.kpop",
  "opt.int.popculture",
  "opt.int.rockmetal",
  "opt.int.podcast",
  "opt.int.guitar",
  "opt.int.photography",
  "opt.int.cs2",
  "opt.int.dota2",
  "opt.int.playstation",
  "opt.int.mobile",
  "opt.int.boardgames",
  "opt.int.running",
  "opt.int.gym",
  "opt.int.football",
  "opt.int.volleyball",
  "opt.int.chess",
  "opt.int.coffee",
  "opt.int.books",
  "opt.int.travel",
  "opt.int.cooking",
  "opt.int.memes",
  "opt.int.astrology",
  "opt.int.psychology",
  "opt.int.volunteer",
] as const;

// Goal keys
export const GOAL_KEYS = [
  "opt.goal.englishb2",
  "opt.goal.ielts",
  "opt.goal.turkish",
  "opt.goal.speaking",
  "opt.goal.academicEng",
  "opt.goal.startup",
  "opt.goal.pitchdeck",
  "opt.goal.nocode",
  "opt.goal.hackathon",
  "opt.goal.incubator",
  "opt.goal.icpc",
  "opt.goal.frontend",
  "opt.goal.backend",
  "opt.goal.uiux",
  "opt.goal.threed",
  "opt.goal.ai",
  "opt.goal.debates",
  "opt.goal.intlaw",
  "opt.goal.mootcourt",
  "opt.goal.lawarticle",
  "opt.goal.gpa",
  "opt.goal.thesis",
  "opt.goal.internship",
  "opt.goal.sessionA",
  "opt.goal.research",
  "opt.goal.erasmus",
  "opt.goal.clubleader",
  "opt.goal.scopus",
  "opt.goal.timemanagement",
  "opt.goal.softskills",
] as const;